image: docker:latest

services:
  - docker:dind

build-master:
  stage: build
  only:
    - master
  variables:
    DOCKER_FULL_PATH: index.docker.io/polyswarm/ambassador

    
  script:
    - docker login -u "$CI_CUSTOM_DOCKER_HUB_USERNAME" -p "$CI_CUSTOM_DOCKER_HUB_PASSWORD" $CI_CUSTOM_DOCKER_HUB_URI && docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .
    - docker push "$DOCKER_FULL_PATH"


build:
  stage: build

  variables:
    DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"

  script:
    - docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .
  except:
    - master
