# Official docker image.
image: docker:latest

services:
  - docker:dind


build-master:
  stage: build
  only:
    - master
  variables:
    DOCKER_FULL_PATH: index.docker.io/polyswarm/ambassador
    
  script:
    - docker login -u "$SWARM_DOCKER_USER" -p "$SWARM_DOCKER_PASSWORD" $DOCKER_SWARM_REGISTRY && docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .
    - docker push "$DOCKER_FULL_PATH"


build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
